### ISSUE TITLE
Ran "Reset the demo project", JDS project now showing errors

### ISSUE THREAD

**Issue by alberttwong** [RedHatEMEA/demobuilder#67]
Ran "Reset the demo project", JDS project now showing errors.  

eclipse.buildId=unknown
java.version=1.8.0_51
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.jboss.devstudio.core.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product com.jboss.devstudio.core.product

This is a continuation of log file /home/demo/workspace/.metadata/.bak_1.log
Created Time: 2015-09-15 16:49:53.110

org.eclipse.core.jobs
Error
Tue Sep 15 16:49:53 UTC 2015
An internal error occurred during: "JPA Project Change Event Handler".

java.lang.NoClassDefFoundError: org/hibernate/eclipse/nature/HibernateNature
	at org.jboss.tools.hibernate.jpt.core.internal.HibernateJpaProject.getDefaultConsoleConfiguration(HibernateJpaProject.java:86)
	at org.jboss.tools.hibernate.jpt.core.internal.HibernateJpaProject.synchronizeJpaFiles(HibernateJpaProject.java:273)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject$InternalResourceDeltaVisitor.fileChangeIsSignificant(AbstractJpaProject.java:1632)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject$ResourceDeltaVisitor.fileChanged(AbstractJpaProject.java:1824)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject$ResourceDeltaVisitor.visit(AbstractJpaProject.java:1816)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject$ResourceDeltaVisitor.visitDelta(AbstractJpaProject.java:1799)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.internalProjectChanged(AbstractJpaProject.java:1610)
	at org.eclipse.jpt.jpa.core.internal.AbstractJpaProject.projectChanged(AbstractJpaProject.java:1602)
	at org.eclipse.jpt.jpa.core.internal.InternalJpaProjectManager.projectChanged_(InternalJpaProjectManager.java:764)
	at org.eclipse.jpt.jpa.core.internal.InternalJpaProjectManager$ProjectChangeEventHandlerCommand.execute(InternalJpaProjectManager.java:746)
	at org.eclipse.jpt.common.core.internal.utility.command.JobCommandJob.run(JobCommandJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by alberttwong** [comment]
So I skipped this.   I just now "vagrant destroy" and "vagrant up".
